name: Minify and Upload to S3

on:
  push:
    branches:
      - main

jobs:
  minify-and-upload-to-s3:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v6

      - name: Minify HTML
        run: |
          npx html-minifier-terser \
            --collapse-whitespace \
            --remove-comments \
            --minify-css true \
            --minify-js true \
            -o index.min \
            index.html

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/jluszcz.com.github
          role-session-name: github-upload
          aws-region: us-east-1

      - name: Upload to S3
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: aws s3 cp index.min s3://jluszcz.com/index.html
