name: Upload to S3

on:
  push:
    branches:
      - main
    paths:
      - index.html

jobs:
  upload-to-s3:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/jluszcz.com.github
          role-session-name: github-upload
          aws-region: us-east-1

      - name: Upload to S3
        env:
          AWS_DEFAULT_REGION: us-east-1
        run: aws s3 cp index.html s3://jluszcz.com/index.html
